version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_USER=user
      - POSTGRES_DB=test_db
  # web:
  #   build: .
  #   ports:
  #     - "5000:5000"